### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by snc** [KnpLabs/PiwikClient#1]
Regarding to the README from the KnpPiwikBundle, this bundle should be located at `git://github.com/knplabs/KnpPiwikClient.git`.

So maybe you should rename the repository or change the KnpPiwikBundle README?

**Comment by tzi** [comment]
Hi!

I'm a not using Symfony a lot, but I don't see any interest in repeating the organization name in the repository name.

Cheers,
Thomas.

**Comment by docteurklein** [comment]
closing for now.
