### ISSUE TITLE
Proposal > call arguments

### ISSUE THREAD

**Issue by tzi** [KnpLabs/PiwikClient#6]
Hi!

This is a proposal. If you accept it on the principle, I will make a PR with the updated code, tests & docs.

---

Could we cut the call() $method argument in two parts?

``` php
// For the moment
$client->call('API.getReportMetadata', array(), 'php');
$client->call('Plugin.method', $params, $format);
// Proposition
$client->call('API', 'getReportMetadata', array(), 'php');
$client->call($plugin, $method, $params, $format);
```

This could make a good abstraction of the Piwik API structure.

Cheers,
Thomas.

**Comment by inoryy** [comment]
I'm not sure this outweighs BC break issues. And it's actually listed like that in the [docs](http://piwik.org/docs/analytics-api/reference/#API), so with current version I can simply copy/paste method names.

What's the use case?

**Comment by tzi** [comment]
Hi @Inori!

I know that's will break the backward compatibility, so I would understand if it was not accepted.
It is just an idea that I had when I was using this library, not sure it worth it. 

My point is that an API client is here to abstract the actual API format. So it is not big deal to have a different formats that the official documentation.
Separate the `$method` argument in two is a future-ready improvement, it will allow us:
- To have a clearer first argument.
- To maybe add controls on both arguments.
- To use it easier in a debug/error trace.

See you,
Thomas.

**Comment by docteurklein** [comment]
closing for now.
