### ISSUE TITLE
Proposal > remove license file header

### ISSUE THREAD

**Issue by tzi** [KnpLabs/PiwikClient#7]
Hi!

This is a proposal. If you accept it on the principle, I will make a PR with the updated code, tests & docs.

---

Could we remove the license headers on every file?
We juste have to keep the README & LICENSE files.

It simpler and it seems to be what you do on your other projets.

Cheers,
Thomas.

**Comment by inoryy** [comment]
Sure, makes sense

**Comment by tzi** [comment]
Cool!
